name: web_build

on: [push, pull_request]

env:
  CMAKE_GENERATOR: Ninja

jobs:
  web-build:
    defaults:
      run:
        shell: bash

    name: WebAssembly Build (Emscripten)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install Emscripten (v4.0.2)
        run: |
          git clone --depth=1 -b 4.0.2 https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install 4.0.2
          ./emsdk activate 4.0.2
          echo "source $(pwd)/emsdk_env.sh" >> $GITHUB_ENV

      - name: Configure (CMake with Emscripten)
        run: |
          source emsdk/emsdk_env.sh
          emcmake cmake -S . -B build -DEMSCRIPTEN_FORCE_COMPILERS=OFF -Dstay3_BUILD_TESTS=ON -Dstay3_BUILD_EXAMPLES=ON

      - name: Build (WebAssembly)
        run: cmake --build build -j4

      - name: Upload Web Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/*

