name: web_build

on: [push, pull_request]

jobs:
  web-build:
    defaults:
      run:
        shell: bash

    name: Build on Windows

    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: tot

      - name: Configure
        run: |
          git submodule update --init --remote
          emcmake cmake -S . -B build -DEMSCRIPTEN_FORCE_COMPILERS=OFF -DCMAKE_BUILD_TYPE=Release -Dstay3_BUILD_TESTS=ON -Dstay3_BUILD_EXAMPLES=ON -GNinja

      - name: Build
        run: cmake --build build -j4

      - name: Prepare test environment
        run: |
          cd test/web
          npm i

      - name: Test
        run: ctest --test-dir build/test --output-on-failure
