name: web_build

on: [push, pull_request]

env:
  CMAKE_GENERATOR: Ninja

jobs:
  web-build:
    defaults:
      run:
        shell: bash

    name: WebAssembly Build (Emscripten)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: sudo apt-get install libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev mesa-common-dev libx11-xcb-dev pkg-config nodejs npm

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.2

      - name: Install clang-tools
        run: sudo apt install clang-tools-19 && ln -s /usr/bin/clang-scan-deps-19 /usr/local/bin/clang-scan-deps

      - name: Configure
        run: |
          git submodule update --init --remote --depth=1
          emcmake cmake -S . -B build -DEMSCRIPTEN_FORCE_COMPILERS=OFF -Dstay3_BUILD_TESTS=ON -Dstay3_BUILD_EXAMPLES=ON

      - name: Build
        run: cmake --build build -j4

      - name: Test
        run: ctest --test-dir build/test --output-on-failure