name: web_build

on: [push, pull_request]

env:
  DISPLAY: :99

jobs:
  web-build:
    defaults:
      run:
        shell: bash

    name: Build on Ubuntu

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y nodejs npm xorg-dev xvfb fluxbox

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Configure
        run: |
          git submodule update --init --remote
          emcmake cmake -S . -B build -DEMSCRIPTEN_FORCE_COMPILERS=OFF -DCMAKE_BUILD_TYPE=Release -Dstay3_BUILD_TESTS=ON -Dstay3_BUILD_EXAMPLES=ON -GNinja

      - name: Build
        run: cmake --build build -j4

      - name: Prepare test environment
        run: |
          Xvfb $DISPLAY -screen 0 1920x1080x24 &
          sleep 5
          fluxbox > /dev/null 2>&1 &
          sleep 5
          cd test/web
          npm i

      - name: Test
        run: ctest --test-dir build/test --output-on-failure
