name: web_build

on: [push, pull_request]

env:
  CMAKE_GENERATOR: Ninja

jobs:
  web-build:
    defaults:
      run:
        shell: bash

    name: Build on ubuntu

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install nodejs npm

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: tot

      - name: Configure
        run: |
          git submodule update --init --remote --depth=1
          emcmake cmake -S . -B build -DEMSCRIPTEN_FORCE_COMPILERS=OFF -DCMAKE_BUILD_TYPE=Release -Dstay3_BUILD_TESTS=ON -Dstay3_BUILD_EXAMPLES=ON

      - name: Build
        run: cmake --build build -j4

      - name: Test
        run: |
          cd test/web && npm i && cd ../../
          ctest --test-dir build/test --output-on-failure