name: build_and_test

on: [push, pull_request]

env:
  CMAKE_GENERATOR: Ninja
  DISPLAY: :99

jobs:

  build:

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        platform: 
          # - { name: Ubuntu with gcc, os: ubuntu-latest, pkg: g++, compiler: g++, version: 14 }
          - { name: Ubuntu with clang, os: ubuntu-latest, pkg: clang, compiler: clang++, version: 18 }
          - { name: Windows with MSVC, os: windows-latest }
        buildType: ["Debug"]

    name: ${{ matrix.platform.name }} - ${{ matrix.buildType }}

    runs-on: ${{ matrix.platform.os }}

    steps:

      - name: Checkout source
        uses: actions/checkout@v4
      
      - name: Install build dependencies (Linux)
        if: contains(matrix.platform.os, 'ubuntu')
        run: sudo apt-get install libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev mesa-common-dev libx11-xcb-dev pkg-config nodejs npm libwayland-dev libxkbcommon-dev xorg-dev xvfb fluxbox

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
    
      - name: Install MSVC (Windows)
        if: contains(matrix.platform.name, 'MSVC')
        uses: ilammy/msvc-dev-cmd@v1
      
      - name: Install compiler (Linux)
        if: contains(matrix.platform.name, 'ubuntu')
        run: |
          sudo apt update
          sudo apt install -y ${{ matrix.platform.pkg }}-${{ matrix.platform.version }}
          echo "CXX=${{ matrix.platform.compiler }}-${{ matrix.platform.version }}" >> "$GITHUB_ENV"

      - name: Configure
        run: |
          git submodule update --init --remote --depth=1
          cmake -S . -B build -Dstay3_BUILD_TESTS=ON -Dstay3_BUILD_EXAMPLES=ON -DCMAKE_BUILD_TYPE=${{ matrix.buildType }}
    
      - name: Build
        run: cmake --build build -j4

      - name: Create graphics server (Linux)
        if: contains(matrix.platform.name, 'ubuntu')
        run:
          Xvfb $DISPLAY -screen 0 1920x1080x24 &
          sleep 5
          fluxbox > /dev/null 2>&1 &
          sleep 5

      - name: Test
        run: ctest --test-dir build/test --output-on-failure
